apiVersion: v1
kind: ConfigMap
metadata:
  name: post-configmap
data:
  ENVIRONMENT: "develop"
  PORT: "3001"
  VERSION: "1.0"
  USERS_PATH: "http://delivery-together-user-service:3000"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-configmap
data:
  NODE_ENV: "development"
  APP_PORT: "3000"
  VERSION: "1.0"