version: '3.8'

services:
  posts:
    container_name: delivery-together-post-api
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
       ENVIRONMENT: develop
       PORT: 3001
       VERSION: 1.0
       DB_USER: postgres
       DB_PASSWORD: postgres
       DB_HOST: posts_db
       DB_PORT: 5432
       DB_NAME: post-db
       USERS_PATH: http://users:3000
    volumes:
      - .:/usr/src/app
    networks:
      - post_net
      - app_net
    depends_on:
      - posts_db
      - users
    links:
      - posts_db
      - users
  posts_db:
    container_name: post-db
    image: postgres:latest
    env_file:
      - .env.db
    volumes:
      - post-db:/var/lib/postgresql/data
    networks:
      - post_net
  users:
      container_name: delivery-together-user-api
      build: ../delivery-together-user-api/.
      ports:
        - "3000:3000"
      environment:
       NODE_ENV: development
       APP_PORT: 3000
       DB_USER: postgres
       DB_PASSWORD: postgres
       DB_HOST: users_db
       DB_PORT: 5432
       DB_NAME: user-db
      networks:
        - user_net
        - app_net
      depends_on:
        - users_db
      links:
        - users_db
  users_db:
    container_name: user-db
    image: postgres
    env_file:
      - ../delivery-together-user-api/.env.db
    volumes:
      - user-db:/var/lib/postgresql
    networks:
      - user_net
networks:
  post_net:
    name: post_net
    internal: true
  app_net:
    name: app_net
  user_net:
    name: user_net
volumes:
  post-db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/postgres
  user-db: