###################################
# delivery-together-score-api
###################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-together-score-api
  labels:
    app: delivery-together-score-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-together-score-api
  template:
    metadata:
      labels:
        app: delivery-together-score-api
    spec:
      containers:
        - name: delivery-together-score-api
          image: us-central1-docker.pkg.dev/esoteric-realm-415003/delivery-together-repository/delivery-together-score-api:1.0.5
          env:
            - name: "NODE_ENV"
              valueFrom:
                configMapKeyRef:
                  name: score-configmap
                  key: NODE_ENV
            - name: "APP_ENV"
              valueFrom:
                configMapKeyRef:
                  name: score-configmap
                  key: APP_ENV
            - name: "PORT"
              valueFrom:
                configMapKeyRef:
                  name: score-configmap
                  key: PORT
            - name: "USERS_PATH"
              valueFrom:
                configMapKeyRef:
                  name: score-configmap
                  key: USERS_PATH
            - name: "DEBUG"
              valueFrom:
                configMapKeyRef:
                  name: score-configmap
                  key: DEBUG
            - name: "LOG_LEVEL"
              valueFrom:
                configMapKeyRef:
                  name: score-configmap
                  key: LOG_LEVEL
            - name: "DB_USER"
              valueFrom:
                secretKeyRef:
                  name: score-secrets 
                  key: DB_USER
            - name: "DB_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: score-secrets 
                  key: DB_PASSWORD
            - name: "DB_HOST"
              valueFrom:
                secretKeyRef:
                  name: score-secrets 
                  key: DB_HOST
            - name: "DB_PORT"
              valueFrom:
                secretKeyRef:
                  name: score-secrets 
                  key: DB_PORT
            - name: "DB_NAME"
              valueFrom:
                secretKeyRef:
                  name: score-secrets 
                  key: DB_NAME
          ports:
            - containerPort: 3004
          imagePullPolicy: Always

---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: delivery-together-score-config
spec:
  healthCheck:
    checkIntervalSec: 30
    port: 3004
    type: HTTP
    requestPath: /scores/ping
---
apiVersion: v1
kind: Service
metadata:
  name: delivery-together-score-service
  annotations:
    cloud.google.com/backend-config: '{"default": "delivery-together-score-config"}'
spec:
  type: NodePort
  selector:
    app: delivery-together-score-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3004
      nodePort: 31001