version: "3.9"

services:
  mailer:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: delivery-together-mailer-api
    volumes: 
      - ".:/app"
    restart: on-failure
    ports:
      - "3006:8000"
    tty: true