version: "3.9"
services:

  routes:
    container_name: delivery-together-route-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    restart: always
    environment:
      ENVIRONMENT: develop
      FLASK_APP: src/app
      PORT: 3002
      VERSION: 1.0
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: routes_db
      DB_PORT: 5432
      DB_NAME: route-db
      USERS_PATH: http://users:3000
    volumes:
      - .:/usr/src/app
    networks:
      - route_net
      - app_net
    depends_on:
      - routes_db
      - users
    links:
      - routes_db
      - users
  routes_db:
    container_name: routes-db
    image: postgres:latest
    env_file:
      - .env.db
    volumes:
      - "./data/postgres:/var/lib/postgresql"
    networks:
      - route_net
  users:
    container_name: delivery-together-user-api
    build: ../delivery-together-user-api/.
    ports:
      - "3000:3000"
    environment:
       NODE_ENV: development
       APP_PORT: 3000
       DB_USER: postgres
       DB_PASSWORD: postgres
       DB_HOST: users_db
       DB_PORT: 5432
       DB_NAME: user-db
    networks:
      - user_net
      - app_net
    depends_on:
      - users_db
    links:
      - users_db
  users_db:
    container_name: user-db
    image: postgres:latest
    env_file:
      - ../delivery-together-user-api/.env.db
    volumes:
      - ../delivery-together-user-api/data/postgres:/var/lib/postgresql
    networks:
      - user_net

networks:
  route_net:
    name: route_net
    driver: bridge
  app_net:
    name: app_net
    driver: bridge
  user_net:
    name: user_net
    internal: true

volumes:
  user-db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/postgres
