// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using delivery_together_offer_api.Context;

#nullable disable

namespace delivery_together_offer_api.Migrations
{
    [DbContext(typeof(OfferContext))]
    partial class OfferContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("delivery_together_offer_api.Models.Offer", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<DateTime>("createdat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<bool>("fragile")
                        .HasColumnType("boolean");

                    b.Property<decimal>("offer")
                        .HasColumnType("numeric");

                    b.Property<string>("postid")
                        .HasColumnType("text");

                    b.Property<string>("size")
                        .HasColumnType("text");

                    b.Property<string>("userid")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("offer");
                });
#pragma warning restore 612, 618
        }
    }
}
