version: "3.9"
services:

  bff:
    container_name: delivery-together-bff-api-single
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
    environment:
      ENVIRONMENT: develop
      PORT: 80
      VERSION: 1.0
      USERS_PATH: http://users:3000
      OFFER_PATH: http://offers:3003
      SCORE_PATH: http://scores:3004
      ROUTE_PATH: http://routes:3002
      POST_PATH: http://posts:3001
    volumes:
      - .:/usr/src/app
    networks:
      - bff_net
      - app_net
  

networks:
  bff_net:
    name: bff_net
    driver: bridge
  app_net:
    name: app_net
    driver: bridge
