version: '3.8'

services:  
  users:
    container_name: delivery-together-user-api
    build: ../../delivery-together-user-api/.
    ports:
      - "3000:3000"
    environment:
       NODE_ENV: development
       APP_PORT: 3000
       DB_USER: postgres
       DB_PASSWORD: postgres
       DB_HOST: users_db
       DB_PORT: 5432
       DB_NAME: user-db
    networks:
      - user_net
      - app_net
    depends_on:
      - users_db
    links:
      - users_db
  users_db:
    container_name: user-db
    image: postgres:latest
    env_file:
      - ../../delivery-together-user-api/.env.db
    volumes:
      - ../../delivery-together-user-api/data/postgres:/var/lib/postgresql
    networks:
      - user_net
  offers:
    container_name: delivery-together-offer-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
       ENVIRONMENT: develop
       PORT: 3003
       VERSION: 1.0
       DB_USER: postgres
       DB_PASSWORD: postgres
       DB_HOST: offers_db
       DB_PORT: 5432
       DB_NAME: offer-db
       USERS_PATH: http://users:3000
    volumes:
      - .:/usr/src/app
    networks:
      - offer_net
      - app_net
    depends_on:
      - offers_db
    links:
      - offers_db
  offers_db:
    container_name: offer-db
    image: postgres:latest    
    env_file:
      - .env.db
    volumes:
      - "./data/postgres:/var/lib/postgresql"
    networks:
      - offer_net    
networks:  
  user_net:
    name: user_net
    driver: bridge
  app_net:
    name: app_net
    driver: bridge
  offer_net:
    name: offer_net
    driver: bridge